
# Tech Company Corpus - Dữ liệu về các công ty công nghệ
TECH_CORPUS = [
    "OpenAI được thành lập bởi Sam Altman và Elon Musk vào năm 2015.",
    "Sam Altman là CEO của OpenAI kể từ năm 2019.",
    "OpenAI phát triển mô hình ngôn ngữ GPT-4 vào năm 2023.",
    "OpenAI ra mắt ChatGPT vào tháng 11 năm 2022.",
    "Microsoft đã đầu tư 10 tỷ đô vào OpenAI vào năm 2023.",
    "Google được thành lập bởi Larry Page và Sergey Brin vào năm 1998.",
    "Larry Page và Sergey Brin đều là sinh viên của Đại học Stanford.",
    "Google phát triển mô hình AI có tên Gemini vào năm 2023.",
    "Google mua lại DeepMind vào năm 2014 với giá 500 triệu đô.",
    "DeepMind phát triển AlphaGo, chương trình đánh cờ vây đầu tiên đánh bại con người.",
    "Apple được thành lập bởi Steve Jobs, Steve Wozniak và Ronald Wayne vào năm 1976.",
    "Steve Jobs là CEO của Apple từ năm 1997 đến năm 2011.",
    "Apple phát triển hệ điều hành iOS cho iPhone.",
    "Apple ra mắt iPhone đầu tiên vào năm 2007.",
    "Tim Cook trở thành CEO của Apple vào năm 2011 sau khi Steve Jobs qua đời.",
    "Meta được thành lập bởi Mark Zuckerberg vào năm 2004 với tên Facebook.",
    "Meta đổi tên từ Facebook vào năm 2021.",
    "Meta phát triển mô hình AI mã nguồn mở LLaMA.",
    "Mark Zuckerberg là CEO của Meta.",
    "Meta sở hữu Instagram và WhatsApp.",
    "Amazon được thành lập bởi Jeff Bezos vào năm 1994.",
    "Jeff Bezos là người sáng lập và CEO đầu tiên của Amazon.",
    "Amazon phát triển dịch vụ điện toán đám mây AWS.",
    "Andy Jassy trở thành CEO của Amazon vào năm 2021.",
    "Amazon mua lại Whole Foods vào năm 2017.",
    "Microsoft được thành lập bởi Bill Gates và Paul Allen vào năm 1975.",
    "Satya Nadella là CEO của Microsoft từ năm 2014.",
    "Microsoft phát triển hệ điều hành Windows.",
    "Microsoft mua lại LinkedIn vào năm 2016 với giá 26 tỷ đô.",
    "Microsoft mua lại GitHub vào năm 2018.",
    "NVIDIA được thành lập bởi Jensen Huang vào năm 1993.",
    "Jensen Huang là CEO của NVIDIA.",
    "NVIDIA phát triển chip GPU H100 cho AI.",
    "NVIDIA hợp tác với Microsoft để cung cấp hạ tầng AI.",
    "Tesla được thành lập bởi Elon Musk, Martin Eberhard và Marc Tarpenning vào năm 2003.",
    "Elon Musk là CEO của Tesla.",
    "Tesla phát triển xe điện và công nghệ tự lái.",
    "SpaceX được thành lập bởi Elon Musk vào năm 2002.",
    "Elon Musk cũng là chủ sở hữu của mạng xã hội X (Twitter).",
    "Twitter được Elon Musk mua lại vào năm 2022 và đổi tên thành X.",
]
